CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS_2ANO;
USE BD_GERENCIAR_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    AREA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO DATE NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    FK_ID_PROJETO INTEGER,
    FK_CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID),
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF)
);