USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;

INSERT INTO SUPERMERCADO (SUP_CNPJ,
						SUP_RAZAO_SOCIAL,
                        SUP_TELEFONE,
                        SUP_EMAIL,
                        SUP_ENDERECO_LOGRADOURO,
                        SUP_ENDERECO_NUMERO,
                        SUP_ENDERECO_CIDADE,
                        SUP_ENDERECO_ESTADO)
VALUES                ("123456780000101",
						"Supermercado Grick",
                        "19999999999",
                        "gricktambau@mail.com",
                        "Grick Street",
                        "10000",
                        "Tambacity",
                        "SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ,
						SUP_RAZAO_SOCIAL,
                        SUP_TELEFONE,
                        SUP_EMAIL,
                        SUP_ENDERECO_LOGRADOURO,
                        SUP_ENDERECO_NUMERO,
                        SUP_ENDERECO_CIDADE,
                        SUP_ENDERECO_ESTADO)
VALUES                ("123456780000102",
						"Supermercado BomPreço",
                        "21988887777",
                        "bompreco@mail.com",
                        "Avenida Central",
                        "250",
                        "Paulópolis",
                        "RJ");

INSERT INTO SUPERMERCADO (SUP_CNPJ,
						SUP_RAZAO_SOCIAL,
                        SUP_TELEFONE,
                        SUP_EMAIL,
                        SUP_ENDERECO_LOGRADOURO,
                        SUP_ENDERECO_NUMERO,
                        SUP_ENDERECO_CIDADE,
                        SUP_ENDERECO_ESTADO)
VALUES                ("123456780000103",
						"Supermercado Econômico",
                        "31977776666",
                        "economico@mail.com",
                        "Rua das Flores",
                        "88",
                        "Campogrande",
                        "MG");
                        
INSERT INTO SUPERMERCADO (SUP_CNPJ,
						SUP_RAZAO_SOCIAL,
                        SUP_TELEFONE,
                        SUP_EMAIL,
                        SUP_ENDERECO_LOGRADOURO,
                        SUP_ENDERECO_NUMERO,
                        SUP_ENDERECO_CIDADE,
                        SUP_ENDERECO_ESTADO)
VALUES                ("123456780000104",
						"Supermercado Pague Menos",
                        "51966665555",
                        "paguemenos@mail.com",
                        "Alameda dos Ipês",
                        "312",
                        "Verdejante",
                        "RS");
                        
INSERT INTO SUPERMERCADO (SUP_CNPJ,
						SUP_RAZAO_SOCIAL,
                        SUP_TELEFONE,
                        SUP_EMAIL,
                        SUP_ENDERECO_LOGRADOURO,
                        SUP_ENDERECO_NUMERO,
                        SUP_ENDERECO_CIDADE,
                        SUP_ENDERECO_ESTADO)
VALUES                ("123456780000105",
						"Supermercado Real",
                        "71955554444",
                        "realmarket@mail.com",
                        "Rua das Palmeiras",
                        "45",
                        "Solândia",
                        "BA");

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					 PRO_NOME,
                     PRO_PESO,
                     PRO_QUANTIDADE,
                     PRO_PRECO,
                     PRO_DATA_VALIDADE)
VALUES              ("7891234567890",
					 "Arroz 5kg",
                     5.0,
                     500,
                     26.90,
                     "2025-12-25");
                    
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					 PRO_NOME,
                     PRO_PESO,
                     PRO_QUANTIDADE,
                     PRO_PRECO,
                     PRO_DATA_VALIDADE)
VALUES              ("7899876543210",
					 "Feijão Carioca 1kg",
                     1.0,
                     800,
                     9.50,
                     "2025-10-01");


INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					 PRO_NOME,
                     PRO_PESO,
                     PRO_QUANTIDADE,
                     PRO_PRECO,
                     PRO_DATA_VALIDADE)
VALUES              ("7896543219870",
					 "Macarrão Espaguete 500g",
                     0.5,
                     1000,
                     4.75,
                     "2025-09-20");


INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					 PRO_NOME,
                     PRO_PESO,
                     PRO_QUANTIDADE,
                     PRO_PRECO,
                     PRO_DATA_VALIDADE)
VALUES              ("7893216549870",
					 "Óleo de Soja 900ml",
                     0.9,
                     600,
                     7.80,
                     "2025-08-15");

                     
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,
					 PRO_NOME,
                     PRO_PESO,
                     PRO_QUANTIDADE,
                     PRO_PRECO,
                     PRO_DATA_VALIDADE)
VALUES              ("7898529637410",
					 "Açúcar Refinado 1kg",
                     1.0,
                     700,
                     5.20,
                     "2025-07-30");
                     
INSERT INTO CONSUMIDOR (CON_CPF,
						CON_NOME,
                        CON_TELEFONE,
                        CON_EMAIL)
VALUES
('12345678901', 'Maria Oliveira',     '11999990001', 'maria.oliveira@mail.com'),
('23456789012', 'João Santos',        '21988882222', 'joao.santos@mail.com'),
('34567890123', 'Ana Paula Souza',    '31977773333', 'ana.souza@mail.com'),
('45678901234', 'Carlos Pereira',     '41966664444', 'carlos.pereira@mail.com'),
('56789012345', 'Fernanda Lima',      '51955555555', 'fernanda.lima@mail.com');

INSERT INTO FUNCIONARIO (
    FUN_CPF,
    FUN_NOME,
    FUN_DATA_NASCIMENTO,
    FUN_TELEFONE,
    FUN_EMAIL,
    FUN_CARTEIRA_TRABALHO,
    FUN_BANCO_AGENCIA,
    FUN_BANCO_CONTA,
    FUN_DATA_ADMISSAO,
    FUN_JORNADA_TRABALHO,
    FK_SUP_CNPJ
)
VALUES
('98765432100', 'Lucas Almeida',     '1990-05-12', '11999990001', 'lucas.almeida@mail.com', 'CT12345', '0012', '456789-0', '2020-03-15', '40h semanais', '123456780000101'),
('87654321011', 'Juliana Martins',   '1988-09-25', '21988882222', 'juliana.martins@mail.com', 'CT67890', '0034', '123456-7', '2019-07-01', '36h semanais', '123456780000102'),
('76543210122', 'Rafael Costa',      '1995-11-10', '31977773333', 'rafael.costa@mail.com', 'CT11223', '0021', '987654-3', '2021-01-10', '44h semanais', '123456780000103'),
('65432101233', 'Beatriz Rocha',     '1992-04-18', '41966664444', 'beatriz.rocha@mail.com', 'CT33445', '0007', '654321-1', '2018-11-20', '40h semanais', '123456780000104'),
('54321012344', 'Pedro Henrique',    '1998-02-07', '51955555555', 'pedro.henrique@mail.com', 'CT55667', '0010', '321987-5', '2022-06-05', '30h semanais', '123456780000105');

INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES
('123456780000101', 1),
('123456780000101', 2),
('123456780000102', 3),
('123456780000103', 4),
('123456780000104', 5);

INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES
('12345678901', 1),
('23456789012', 2),
('34567890123', 3),
('45678901234', 4),
('56789012345', 5);

SELECT * FROM SUPERMERCADO;

/*
CONSULTAR O AUMENTO DE R$2,00 NO PEÇO DOS PRODUTOS COM PREÇO ATUAL >= R$5,00
*/

SELECT 	PRO_NOME 					AS "NOME",
		PRO_CODIGO_BARRAS		 	AS "CÓDIGO DE BARRAS",
        PRO_PRECO 					AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO + 2),2)	AS "PREÇO COM AJUSTE DE R$2,00"
FROM	PRODUTO
WHERE	PRO_PRECO >= 5;

/*
CONSULTAR A REDUÇÃO DE R$1,00 NO PREÇO DOS PRODUTOS COM PREÇO ABAIXO DE R$5,00
*/
SELECT	PRO_NOME 					AS "NOME",
		PRO_CODIGO_BARRAS 			AS "CÓDIGO DE BARRAS",
        PRO_PRECO 					AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO - 1),2) AS "PREÇO COM REDUÇÃO DE R$1,00"
FROM PRODUTO
WHERE PRO_PRECO <= 10;

/* 
CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS
*/
SELECT	PRO_NOME 			AS "NOME",
		PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
        PRO_PRECO 			AS "PREÇO ATUAL",
        (PRO_PRECO - (PRO_PRECO * 0.1))AS "PREÇO CPM DESCONTO DE 10%"
FROM PRODUTO;

/*AJUSTAR O PRIMEIRO ESTOQUE DO PRODUTO, DIVIDINDO PELA METADE*/
SELECT	PRO_ID,
		PRO_NOME,
		PRO_CODIGO_BARRAS,
        PRO_QUANTIDADE
FROM PRODUTO;

UPDATE PRODUTO
SET PRO_QUANTIDADE = PRO_QUANTIDADE/2
WHERE PRO_ID = 1;

/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM DATA DE VALIDADE ENTRE SETEMBRO DE 2025 E DEZEMBRO DE 2025*/
SELECT	PRO_NOME			AS "NOME",
		PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
        PRO_DATA_VALIDADE 	AS "DATA DE VALIDADE"
FROM    PRODUTO
WHERE   PRO_DATA_VALIDADE BETWEEN '2025-09-01' AND '2025-12-31';

/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇO MAIOR QUE R$ 10 OU MAIOR QUE R$4*/
SELECT	PRO_NOME			AS "NOME",
		PRO_CODIGO_BARRAS 	AS "CODIGO DE BARRAS",
        PRO_PRECO 			AS "PREÇO"
FROM 	PRODUTO
WHERE	PRO_PRECO >=10 OR PRO_PRECO <=4;

/*CONSULTAR OS DDS E TELEFONE DOS CONSUMIDORES SEPARADAMENTE*/
SELECT	CON_NOME					AS "NOME DO CONSUMIDOR",
		CON_CPF						AS "CPF DO CONSUMIDOR",
        SUBSTRING(CON_TELEFONE,1,2) AS "DDD DO TELEFONE",
        SUBSTRING(CON_TELEFONE,3,9) AS "NUMERO DO TELEFONE"
FROM CONSUMIDOR;

/*GERAR UMA FRASE CONCATENANDO:
RAZÃO SOCIAL, CNPJ, TELEFONE E EMAIL*/
SELECT	CONCAT("RAZÃO SOCIAL: ", 
				CONCAT(SUP_RAZAO_SOCIAL,
                CONCAT(" | CNPJ: ",
                CONCAT(SUP_CNPJ,
                CONCAT(" | Telefone: ",
                CONCAT(SUP_TELEFONE,
                CONCAT(" | Email: ", SUP_EMAIL))))))) AS FRASE

FROM SUPERMERCADO;


/*GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS,
REGRAS:
1) QUANTIDADE <= 25: ESTOQUE BAIXO
2) QUANTIDADE > 25 E QUANTIDADE <=100: ESTOQUE MÉDIO 
3) QUANTIDADE > 100: ESTOQUE ALTO*/

SELECT	PRO_NOME 			AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS	AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE		AS "QUANTIDADE",
        CASE
			WHEN PRO_QUANTIDADE <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QUANTIDADE > 25 AND PRO_QUANTIDADE < 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QUANTIDADE >= 100 THEN "ESTOQUE ALTO"
		END AS "NÍVEL DE ESTOQUE"
FROM PRODUTO;

/*GERAR UMA CONSULTA QUE VERIFICA O PESO DOS PRODUTOS,
RETORNAR: NOME, CODIGO DE BARRAS, QUANTIDADE, PESOE DATA DE VALIDADE
REGRAS:
1) PESO <= 5: BAIXO
2) PESO > 5 E PESO <=50: PESO MÉDIO 
3) PESO >=50: PESO ALTO*/

SELECT	PRO_NOME 			AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS	AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE		AS "QUANTIDADE",
        CASE
			WHEN PRO_QUANTIDADE <= 5 THEN "BAIXO"
            WHEN PRO_QUANTIDADE > 5 AND PRO_QUANTIDADE <=50 THEN "PESO MÉDIO"
            WHEN PRO_QUANTIDADE >= 50 THEN "PESO ALTO"
		END AS "PESO DOS PRODUTOS"
FROM PRODUTO;

/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/
SELECT	COUNT(*)
FROM	CONSUMIDOR;

/*CONTAR QUANTOS SUPERMERCADOS TEMOS CADASTRADOS*/
SELECT	COUNT(*)
FROM	SUPERMERCADO;

/*CONTAR QUANTOS PRODUTOS TEMOS CADASTRADOS*/
SELECT	COUNT(*)
FROM	PRODUTO;

/*SOMAR O PREÇO TOTAL DE TODOS OS PRDUTOS CADASTRADOS*/
SELECT	SUM(PRO_PRECO)
FROM	PRODUTO;

SELECT CONCAT("R$ ", TRUNCATE(SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM	PRODUTO;

/*CALCULAR A MÉDIA DE PREÇOS DOS PRODUTOS*/
SELECT AVG(PRO_PRECO)
FROM PRODUTO;

SELECT	CONCAT("R$", TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDIA DE PREÇO"
FROM	PRODUTO;

/*SELECIONAR O PRODUTO MAIS CARO*/
SELECT MAX(PRO_PRECO)
FROM PRODUTO;

/*SELECIONAR O ESTOQUE COM MAIOR QUANTIDADE*/
SELECT MAX(PRO_QUANTIDADE)
FROM PRODUTO;

/*SELECIONAR O PRODUTO MAIS BARATO*/
SELECT	MIN(PRO_PRECO)
FROM	PRODUTO;

/*SELECIONAR O ESTOQUE COM MENOR QUANTIDADE*/
SELECT MIN(PRO_QUANTIDADE)
FROM PRODUTO;

/*SELECIONAR A DATA E HORA ATUAL*/
SELECT NOW() FROM DUAL;

SELECT	FUN_NOME AS "NOME DO FUNCIOÁRIO",
		DATE_FORMAT(FUN_DATA_NASCIMENTO,"%d/%m/%Y")		AS "DATA DE NASCIMENTO", 
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) 	AS "IDADE"
FROM FUNCIONARIO;

/*FUNÇÕES MATEMATICAS
ABS - VALOR ABSOLUTO DE UM NUMERO
ROUND - ARREDONDAR
POWER - POTENCIA*/

SELECT	ABS(-10),
		ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
        POWER(PRO_PRECO,2) AS "PREÇO ELEVADO AO QUADRADO"
FROM PRODUTO;

/*UPPER, LOWER, TRIM*/
SELECT	UPPER(FUN_NOME) AS "MAIUSCULAS",
		LOWER(FUN_NOME) AS "MINUSCULAS",
        TRIM("        Laura") AS "TIRANDO ESPAÇOS"
FROM FUNCIONARIO;

/*AGRUPANDO AS COISAS DE ACORDO COM O CRITÉRIO EM QUE COLOCAMOS*/
SELECT		PRO_QUANTIDADE,
			COUNT(*) AS "REPETIÇÕES"
FROM		PRODUTO
GROUP BY 	PRO_QUANTIDADE;

/*UNION*/
SELECT	FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO
UNION
SELECT	FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO;

SELECT * FROM PRODUTO;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION
SELECT	"Arroz 5kg"
FROM	DUAL
UNION	
SELECT	"Iogurt do Bob Esponja"
FROM DUAL;	
		
/*UNION ALL - UNE AS COISAS NÃO LIGANDO PARA A REPETIÇÃO*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION ALL
SELECT	"Arroz 5kg"
FROM	DUAL
UNION	ALL
SELECT	"Iogurt do Bob Esponja"
FROM DUAL;		

/*SELECT COM WHERE*/
SELECT	FUN_NOME				AS "NOME DO FUNCIONARIO",
		FUN_CPF					AS "CPF DO FUNCIONARIO",
        FUN_DATA_NASCIMENTO		AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM FUNCIONARIO
WHERE	TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) >= 25
AND		TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) <= 35;

/*RETORNAR OS FUNCIONARIO, CONSUMIDORES E SUPERMERCADOS COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
SELECT	CON_NOME		AS "NOME",
		CON_CPF			AS"CPF/CNPJ",
        CON_TELEFONE	AS "TELEFONE",
        CON_EMAIL		AS "EMAIL",
        "CONSUMIDOR"	AS "TIPO"
FROM	CONSUMIDOR
WHERE	UPPER(CON_EMAIL) LIKE "%MAIL%"
OR		UPPER(CON_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT	FUN_NOME		AS "NOME",
		FUN_CPF			AS"CPF/CNPJ",
        FUN_TELEFONE	AS"TELEFONE",
        FUN_EMAIL		AS"EMAIL",
        "FUNCIONARIO"	AS "TIPO"
FROM	FUNCIONARIO
WHERE	UPPER(FUN_EMAIL) LIKE "%MAIL%"
OR 		UPPER(FUN_EMAIL) LIKE "%OUTLOOK%";

SELECT	SUP_RAZAO_SOCIAL	AS "NOME",
		SUP_CNPJ			AS"CPF/CNPJ",
        SUP_TELEFONE		AS "TELEFONE",
        SUP_EMAIL			AS "EMAIL",
        "SUPERMERCADO"		AS "TIPO"
FROM	SUPERMERCADO
WHERE	UPPER(SUP_EMAIL) LIKE "%MAIL%"
OR		UPPER(SUP_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT	SUP_RAZAO_SOCIAL	AS "NOME",
		SUP_CNPJ			AS "CPF/CNPJ",
		SUP_TELEFONE		AS"TELEFONE",
		SUP_EMAIL			AS"EMAIL",
        "SUPERMERCADO"		AS "TIPO"
FROM	SUPERMERCADO
WHERE	UPPER(SUP_EMAIL) LIKE "%MAIL%"
OR 		UPPER(SUP_EMAIL) LIKE "%OUTLOOK%";

/*CROSS JOIN: RETORNAR TODOS OS PRODUTOS EM QUE SÃO VENDIDOS*/
SELECT		PRODUTO.PRO_NOME				AS "NOME",
			PRODUTO.PRO_CODIGO_BARRAS		AS "CODIGO DE BARRAS",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS "RAZÃO SOCIAL"
FROM 		SUPERMERCADO_PRODUTO
CROSS JOIN 	SUPERMERCADO
CROSS JOIN 	PRODUTO
WHERE		PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID
AND			SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;

/*INNER JOIN: RETORNA APENAS OS PRODUTOS QUE FORAM COMPRADOS POR ALGUM CONSUMIDOR*/
SELECT	PRODUTO_CONSUMIDOR.PCO_ID AS "ID DA COMPRA",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO",
        PRODUTO.PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
        CONSUMIDOR.CON_CPF AS "CPF DO CONSUMIDOR"
FROM    PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*EXERCÍCIO INNER JOIN: RETORNAR APENAS OS FUNCIONARIOS QUE TRABALHAM EM UM SUPERMERCADO, RETORNAR O NOME DO FUNCIONARIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/
SELECT	FUN_NOME			AS "NOME DO FUNCIONARIO",
		SUP_RAZAO_SOCIAL 	AS "NOME SUPERMERCADO"
FROM    FUNCIONARIO
INNER JOIN SUPERMERCADO ON (FK_SUP_CNPJ = SUP_CNPJ);

/*EXERCICIO 2 COM INNER JOIN: RETORNAR APENAS OS PRODUTOS QUE EXISTAM EM UM SUPERMERCADO, RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCDO QUE ELE ESTA DISPONIVEL*/
SELECT 		PRODUTO.PRO_NOME				AS "NOME DO PRODUTO",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS "RAZÃO SOCIAL"
FROM 		SUPERMERCADO_PRODUTO
INNER JOIN	PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN	SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*LEFT JOIN */
INSERT INTO PRODUTO		(PRO_CODIGO_BARRAS,
						PRO_NOME,
                        PRO_PESO,
                        PRO_QUANTIDADE,
                        PRO_PRECO,
                        PRO_DATA_VALIDADE)
VALUES					("33333333",
                        "Kit Kat",
                        "30",
                        "1500",
                        4.50,
                        "2026-01-01");
                        
SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

SELECT * FROM SUPERMERCADO;

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO 		ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT *
FROM (
  SELECT    S.SUP_RAZAO_SOCIAL AS RAZAO_SOCIAL,
			F.FUN_NOME         AS NOME_FUNCIONARIO,
			P.PRO_NOME    AS NOME_PRODUTO,
			C.CON_NOME    AS NOME_CONSUMIDOR
  FROM      SUPERMERCADO S
        LEFT JOIN FUNCIONARIO F    			ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
        LEFT JOIN SUPERMERCADO_PRODUTO SP	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
        LEFT JOIN PRODUTO P     			ON (SP.FK_PRO_ID = P.PRO_ID)
        LEFT JOIN PRODUTO_CONSUMIDOR PC  	ON (P.PRO_ID = PC.FK_PRO_ID)
        LEFT JOIN CONSUMIDOR C     			ON (PC.FK_CON_CPF = C.CON_CPF)
        UNION
        SELECT  S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
				F.FUN_NOME         	AS NOME_FUNCIONARIO,
				P.PRO_NOME   		AS NOME_PRODUTO,
				C.CON_NOME    		AS NOME_CONSUMIDOR
		FROM    SUPERMERCADO S
        RIGHT JOIN FUNCIONARIO F    		ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
        RIGHT JOIN SUPERMERCADO_PRODUTO SP  ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
        RIGHT JOIN PRODUTO P     			ON (SP.FK_PRO_ID = P.PRO_ID)
        RIGHT JOIN PRODUTO_CONSUMIDOR PC  	ON (P.PRO_ID = PC.FK_PRO_ID)
        RIGHT JOIN CONSUMIDOR C    			ON (PC.FK_CON_CPF = C.CON_CPF)
)SELECT_EXTERNO
ORDER BY  SELECT_EXTERNO.RAZAO_SOCIAL    ASC,
    SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
          SELECT_EXTERNO.NOME_PRODUTO    ASC,
          SELECT_EXTERNO.NOME_CONSUMIDOR  DESC;

/*EXERCICIO 1*/
SELECT 		PRODUTO.PRO_NOME				AS "NOME DO PRODUTO",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS "RAZÃO SOCIAL"
FROM 		SUPERMERCADO_PRODUTO
INNER JOIN	PRODUTO 						ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN	SUPERMERCADO 					ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*EXERCICIO 2*/
SELECT		FUN_NOME			AS "NOME DO FUNCIONÁRIO",
			SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL"
FROM		FUNCIONARIO
INNER JOIN	SUPERMERCADO ON (FK_SUP_CNPJ = SUP_CNPJ);

/*EXERCICIO 3*/
SELECT	PRODUTO.PRO_NOME AS "NOME DO PRODUTO",
        CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR"
FROM    PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*EXERCICIO 4*/
SELECT	CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM    PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF)
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID);

/*EXERCICIO 5*/
SELECT  SUP_RAZAO_SOCIAL AS "NOME MERCADO",
		COUNT(*) AS "QUANTIDADE"
FROM SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
GROUP BY   SUPERMERCADO.SUP_RAZAO_SOCIAL;