CREATE DATABASE IF NOT EXISTS BD_RESERVA_HOTEL_2ANO;
USE BD_RESERVA_HOTEL_2ANO;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUM INTEGER NOT NULL,
    FK_CNPJ_HOTEL VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_CNPJ_HOTEL) REFERENCES HOTEL(CNPJ)
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_QUARTO INTEGER,
    FK_CPF_HOSPEDE VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO(ID),
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE(CPF)
);